const PROJECT_LIST = [
  {
    id: 1,
    title: 'project name',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt beatae perferendis praesentium quas, aliquid eum libero expedita hic nemo quaerat sit neque, laboriosam non, culpa cupiditate doloribus? Dignissimos, nesciunt repudiandae.',
    url: '',
    img: '',
    skills: [
      'React',
      'Next.js',
      'Node.js',
      'SASS',
      'ContextAPI',
      'javaScript',
      'TypeScript',
      'GSAP',
    ],
  },
  {
    id: 2,
    title: 'project name',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt beatae perferendis praesentium quas, aliquid eum libero expedita hic nemo quaerat sit neque, laboriosam non, culpa cupiditate doloribus? Dignissimos, nesciunt repudiandae.',
    url: '',
    img: '',
    skills: [
      'React',
      'Next.js',
      'Node.js',
      'SASS',
      'ContextAPI',
      'javaScript',
      'TypeScript',
      'GSAP',
    ],
  },
  {
    id: 3,
    title: 'project name',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt beatae perferendis praesentium quas, aliquid eum libero expedita hic nemo quaerat sit neque, laboriosam non, culpa cupiditate doloribus? Dignissimos, nesciunt repudiandae.',
    url: '',
    img: '',
    skills: [
      'React',
      'Next.js',
      'Node.js',
      'SASS',
      'ContextAPI',
      'javaScript',
      'TypeScript',
      'GSAP',
    ],
  },
  {
    id: 4,
    title: 'project name',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt beatae perferendis praesentium quas, aliquid eum libero expedita hic nemo quaerat sit neque, laboriosam non, culpa cupiditate doloribus? Dignissimos, nesciunt repudiandae.',
    url: '',
    img: '',
    skills: [
      'React',
      'Next.js',
      'Node.js',
      'SASS',
      'ContextAPI',
      'javaScript',
      'TypeScript',
      'GSAP',
    ],
  },
];

export default PROJECT_LIST;
